export const STATUS_CODES = {
    INITIAL: 'INITIAL',
    GET_COURSE_REQUESTED: 'GET_COURSE_REQUESTED',
    GET_COURSE_SUCCEEDED: 'GET_COURSE_SUCCEEDED',
    GET_COURSE_FAILED: 'GET_COURSE_FAILED',
  };
